language: cpp
sudo: false

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libboost-all-dev
      - g++-4.9

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

install:
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - cd lcov_1.11 && make -C lcov-1.11 && make install
  - gem install coveralls-lcov
  - g++ --version
  - locv --version
  - cmake --version
  - mkdir build && cd build

before_script:
  - lcov --directory . --zerocounters

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ../
  - make
  - ctest -V

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info