language: cpp
sudo: false

compiler:
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libboost-all-dev
      - g++-4.9

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

install:
  - g++ --version
  - cmake --version
  - mkdir build && cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ../
  - make
  - ctest -V